### ISSUE TITLE
meal sound

### ISSUE THREAD

**Issue by selinux** [PostTenebrasLab/DrinkingBuddyServer#9]
play a sound when someone pay his meal to encourage/remember other people to do it

**Comment by ptlpi** [comment]
I second this - some way to reinforce good behavior would be appreciated, since it is presently clumsy/disruptive for someone to have to shout out that payment is necessary.  There are a variety of ways that we could do this... but a loud drinkingbuddy announcement that someone's meal payment is appreciated would generate some laughs.

```
  From: Sebastien Chassot <notifications@github.com>
```

 To: PostTenebrasLab/DrinkingBuddyServer DrinkingBuddyServer@noreply.github.com 
 Sent: Thursday, November 17, 2016 6:34 PM
 Subject: [PTL-Comite] [PostTenebrasLab/DrinkingBuddyServer] meal sound (#9)

play a sound when someone pay his meal to encourage/remember other people to do it—

**Comment by charafantah** [comment]
Done... we now need to choose a good sound to play. Currently the sound played is "hands clapping"
